openapi: 3.0.0
info:
  title: 学习资料相关 API
  version: 1.0.0
  description: 这是学习资料相关的 API 文档

paths:
  /api/learning-materials:
    get:
      summary: 获取学习资料列表
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: school
          schema:
            type: string
        - in: query
          name: grade
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: 成功获取学习资料列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  materials:
                    type: array
                    items:
                      $ref: "#/components/schemas/LearningMaterial"
                  totalCount:
                    type: integer

  /api/learning-material/{uuid}/structure:
    get:
      summary: 获取学习资料结构
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功获取学习资料结构
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LearningMaterialStructure"

  /api/learning-material/{materialUuid}/section/{sectionUuid}/question/{questionUuid}/detail/{detailIndex}:
    get:
      summary: 获取问题详情
      parameters:
        - in: path
          name: materialUuid
          required: true
          schema:
            type: string
        - in: path
          name: sectionUuid
          required: true
          schema:
            type: string
        - in: path
          name: questionUuid
          required: true
          schema:
            type: string
        - in: path
          name: detailIndex
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 成功获取问题详情
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionDetail"

  /api/learning-material/{materialUuid}/section/{sectionUuid}/question/{questionUuid}/answer:
    post:
      summary: 提交问题答案
      parameters:
        - in: path
          name: materialUuid
          required: true
          schema:
            type: string
        - in: path
          name: sectionUuid
          required: true
          schema:
            type: string
        - in: path
          name: questionUuid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: array
                  items:
                    type: string
                status:
                  type: string
      responses:
        "200":
          description: 成功提交答案
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/learning-material/{uuid}/mistakes:
    post:
      summary: 添加题目到错题集
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                questionUuid:
                  type: string
                questionDetailUuid:
                  type: string
      responses:
        "200":
          description: 成功添加到错题集
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  mistakeId:
                    type: string

components:
  schemas:
    LearningMaterial:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        category:
          type: string
        gradeInfo:
          $ref: "#/components/schemas/GradeInfo"
        publishDate:
          type: string
          format: date
        lastStudyDate:
          type: string
          format: date
        status:
          type: string

    LearningMaterialStructure:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        category:
          type: string
        gradeInfo:
          $ref: "#/components/schemas/GradeInfo"
        publishDate:
          type: string
          format: date
        lastStudyDate:
          type: string
          format: date
        status:
          type: string
        sections:
          type: array
          items:
            $ref: "#/components/schemas/Section"

    QuestionDetail:
      $ref: "./question_api.yaml#/components/schemas/Question"

    GradeInfo:
      type: object
      properties:
        school:
          type: string
        grade:
          type: string
    Section:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        order_in_exam:
          type: integer
        questions:
          type: array
          items:
            $ref: "#/components/schemas/Question"

    Question:
      $ref: "./question_api.yaml#/components/schemas/Question"
